dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0

compiler:
  solc:
    version: 0.8.19
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.9.0/contracts"
    exclude_paths:
      - "contracts/legacy"

networks:
  development:
    host: http://127.0.0.1:8545
    gas_limit: 12000000
    gas_price: 20000000000
    required_confs: 1

  anvil:
    host: http://127.0.0.1:8545
    gas_limit: 12000000
    gas_price: 20000000000
    chain_id: 31337
    required_confs: 1

  mainnet-fork:
    host: http://127.0.0.1:8545
    gas_limit: 12000000
    gas_price: 20000000000
    required_confs: 1
